server {
    charset utf-8;
    client_max_body_size 512M;
    server_name localhost;

    listen 80;

    root /app/frontend/web;
    index index.php index.html index.htm;

    # Frontend — всё, что не /admin
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Backend — доступен по /admin
    location /admin {
        alias /app/backend/web;
        index index.php index.html;

        try_files $uri $uri/ /admin/index.php?$args;

        location ~ ^/admin/.*\.php$ {
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /app/backend/web$fastcgi_script_name;
            fastcgi_pass 127.0.0.1:9000;
        }
    }

    # Статика — кеш
    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar|svg|woff|woff2|eot|ttf|otf)$ {
        expires 6M;
        add_header Last-Modified "";
        log_not_found off;
        try_files $uri =404;
    }

    # PHP-FPM для frontend
    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
        try_files $uri =404;
    }

    # Запрет доступа к скрытым файлам
    location ~ /\.(ht|svn|git) {
        deny all;
    }
}